FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS base
COPY . /app
WORKDIR /app
RUN dotnet build mHS.NEEV.sln
RUN cd ./mHS.NEEV.API/
RUN dotnet publish -c Release -o out

FROM microsoft/dotnet:2.2-aspnetcore-runtime
RUN apt-get update \
   && apt-get install -y --no-install-recommends libgdiplus libc6-dev \
   && rm -rf /var/lib/apt/lists/*
COPY --from=base /app /app
ENTRYPOINT ["dotnet", "/app/mHS.NEEV.API/out/mHS.NEEV.API.dll"]